version: "3.3"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0 
    environment:
        ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /home/ozlevka/tmpwork/elastic:/data
    networks:
      - default
    command: "elasticsearch --E cluster.name=soaktest --E path.data=/data"
    ports:
      - "9201:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0 
    command: kibana -e http://elastic:9200
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5603:5601"
    networks:
      - default
    links:
      - elastic
    depends_on:
      - elastic

  test:
    image: ozlevka/python-test:180621-12.13
    networks:
      - default
    links:
      - elastic
    depends_on:
      - elastic
#    network_mode: host
    environment:
      - "SYSTEM_UNDER_TEST_IP=192.168.50.74"
      - "TEST_CYCLES=500"
      - "ES_HOST=elastic:9200"
      - "ITERATION_PAUSE=10"
      - "CHROME_LOG_PATH=."
#     - "MAXIMUM_TABS=10" in browser

networks:
  default:

