#!/bin/bash 

COUNTER=$(seq 1 "$1")

source ~/.virtualenv/soak/bin/activate


function make_log_directory() {
    if [ ! -d "$1" ]; then
        mkdir -p "$1"
    fi
}

for c in $COUNTER; do
    make_log_directory "./$c"
done

